### ISSUE TITLE
Feature request: follow curve while increase pwm on fancontrol

### ISSUE THREAD

**Issue by skjnldsv** [lm-sensors/lm-sensors#128]
Hey!
Thanks a lot for this awesome software!

I'm using very high rpm fans (12k+) and the slightest change on pwm can get very high  very quickly.
Additionally, the temps provided my the cpu are often spike very high very quickly on use. For example, default temp is `30°C`, I start a big task, 5sec later the temp states `60°C`.

This increase the pwm very quickly. And for short tasks that just create a small spike in the temps, the fan can have its pwm value defined for the whole `$DELAY` (10s of 12k rpm can get very noisy)

My request would be to only increase the pwm progressively. e.g.
`MINPWM=100`, `MAXPWM=200`, `MAXTEMP=70`
Temp go from `20` to `70°C`. Currently, the fancontrol would set PWM at `200` directly.
My suggestion is that it slowly increase from `(200-100)/(70-20)=20` every `$DELAY`.
That way if it's a small spike, the pwm will only be updated to 120 and won't go from 0 to 120 and to 0 again :)

Thanks! :wave:

**Comment by cooper151288** [comment]
Check your processor manual- you may have slew control available- this would do filtering on the temperature signal. a lot of AMD 15h/16h have it available

**Comment by zdzichu** [comment]
Also, newer version of `fancontrol` have `AVERAGE=` settings, which would take last x readings and smooth them. It deals with peaks.

**Comment by skjnldsv** [comment]
AVERAGE  do the job yes, thx!
