### ISSUE TITLE
HP EliteBook 8XX g5 support

### ISSUE THREAD

**Issue by Sponge5** [lm-sensors/lm-sensors#136]
Hi,
I don't have high hopes that my machine would get some special treatment, but one can hope, right?

My machine is HP EliteBook 830 g5 and sensors-detect have trouble finding the Super I/O chip.

The text with SuperIO is here:
```
Some Super I/O chips contain embedded sensors. We have to write to
standard I/O ports to probe them. This is usually safe.
Do you want to scan for Super I/O sensors? (YES/no): Probing for Super-I/O at 0x2e/0x2f
Trying family `National Semiconductor/ITE'...               Yes
Found unknown chip with ID 0x2011
Probing for Super-I/O at 0x4e/0x4f
```

The whole sensors-detect output:
[text.txt](https://github.com/lm-sensors/lm-sensors/files/2476658/text.txt)

In case there's not much hope for help, would you recommend superiotool by coreboot? I'm a bit scared of trusting anyone when it comes to firmware, but right now my fan is blasting even though my CPU is idle and it's quite annoying.

**Comment by micmalti** [comment]
Might I ask if/how did you resolve this issue?
