### ISSUE TITLE
[feature request] sensor from command output

### ISSUE THREAD

**Issue by Paxy** [lm-sensors/lm-sensors#142]
It would be great if you can support a sort of generic sensor that will read a value from command output and display it in sensor list.

For example - CPU frequency sensor could use data from the command: cpufreq-info -f -m

This generic sensor should use a configuration file to get sensor command.

**Comment by olysonek** [comment]
I think this is outside of the scope of lm_sensors. lm_sensors only gathers data from the kernel's hwmon subsystem. If you want an application that gathers various info about the system, you should build one on top of lm_sensors (you may be interested to know that `sensors -j` outputs sensor data in the json format).
