### ISSUE TITLE
Saving config in pwmconfig fails

### ISSUE THREAD

**Issue by alexanderbazhenoff** [lm-sensors/lm-sensors#152]
Executing command `sudo pwmconfig` fails on Debian Stretch with:
```
mv: cannot create regular file 'y': Permission denied
chmod: cannot access 'y': No such file or directory
```
when you set default path (blank $FCCONFIG) or set to 'y' by mistake.

Fixed.

**Comment by olysonek** [comment]
Well, it's not a bug, it's the user who made a mistake.

**Comment by alexanderbazhenoff** [comment]
Yeah, it's not bug, just better usabilty. The default path is shown in brackets when it's prompted. I whought that this is default, pushed "enter" and got an error. I didn't get what the error and what's going on three times, until I looked at the code... LOL As in previous times you could also answer "y". With handling is more userfriendly, but as you wish.

**Comment by olysonek** [comment]
> Yeah, it's not bug, just better usabilty.

I think treating "y" differently could  in fact hurt usability.

> The default path is shown in brackets when it's prompted. I whought that this is default, pushed "enter" and got an error.

It is the default. Just pressing enter should choose the defaut. It does work like that for me.
