### ISSUE TITLE
lm-sensors.org is down

### ISSUE THREAD

**Issue by Talkless** [lm-sensors/lm-sensors#217]
Hi,
man page hinted about http://www.lm-sensors.org/wiki/Configurations page, but it seems whole lm-sensors.org is down..? Browser does not get a response.

**Comment by olysonek** [comment]
Hi. It's been down for a couple of years. The new location is at https://hwmon.wiki.kernel.org/lm_sensors.

Which man page are you talking about? Are you sure you're using a recent lm_sensors version?

**Comment by Talkless** [comment]
Ouch.. Well, no, not the recent version. It's in Debian 9 (stretch). And actually it was not a man page, but `/etc/sensors3.conf`:
```
grep -B1 Configurations /etc/sensors3.conf
# Such custom configuration files for specific mainboards can be found at
# http://www.lm-sensors.org/wiki/Configurations
```

Sorry for the noise, and thanks for the link!

**Comment by olysonek** [comment]
I see. BTW, currently the best place to find configuration files is the repository itself:
https://github.com/lm-sensors/lm-sensors/tree/master/configs
