### ISSUE TITLE
Support for amd r7-4800u!

### ISSUE THREAD

**Issue by flaviusbuffon** [lm-sensors/lm-sensors#266]
My laptop legion5 with manjaro can't detect my cou so i can't get the temperature. The problem are supposed to be solved!
Thanks

**Comment by birdie-github** [comment]
[ZenPower](https://github.com/ocerman/zenpower) already supports your CPU - use it until the official support comes. Also this bug report is invalid. This is a project for the lm-sensors user space application and library.
