### ISSUE TITLE
Add support for ITE IT8572E 

### ISSUE THREAD

**Issue by mohamadali-halwani** [lm-sensors/lm-sensors#275]
My chip is 
ITE 
IT8572E
1119-AXA
DCE9BB

Hardware information

OS: Arch Linux x86_64
Host: G53SW 1.0
Kernel: 5.7.12-arch1-1
Shell: zsh 5.8
CPU: Intel i7-2630QM (8) @ 2.900GHz
GPU: NVIDIA GeForce GTX 460M
 Memory: 2152MiB / 7934MiB

using sensors-detect gives the following output :

# sensors-detect version 3.6.0 
# System: ASUSTeK Computer Inc. G53SW [1.0] (laptop) 
# Kernel: 5.7.12-arch1-1 x86_64 
# Processor: Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (6/42/7) 
This program will help you determine which kernel modules you need 
to load to use lm_sensors most effectively. It is generally safe 
and recommended to accept the default answers to all questions, 
unless you know what you're doing. 
Some south bridges, CPUs or memory controllers contain embedded sensors. 
Do you want to scan for them? This is totally safe. (YES/no): yes 
Module cpuid loaded successfully. 
Silicon Integrated Systems SIS5595...                       No 
VIA VT82C686 Integrated Sensors...                          No 
VIA VT8231 Integrated Sensors...                            No 
AMD K8 thermal sensors...                                   No 
AMD Family 10h thermal sensors...                           No 
AMD Family 11h thermal sensors...                           No 
AMD Family 12h and 14h thermal sensors...                   No 
AMD Family 15h thermal sensors...                           No 
AMD Family 16h thermal sensors...                           No 
AMD Family 17h thermal sensors...                           No 
AMD Family 15h power sensors...                             No 
AMD Family 16h power sensors...                             No 
Hygon Family 18h thermal sensors...                         No 
Intel digital thermal sensor...                             Success! 
    (driver `coretemp') 
Intel AMB FB-DIMM thermal sensor...                         No 
Intel 5500/5520/X58 thermal sensor...                       No 
VIA C7 thermal sensor...                                    No 
VIA Nano thermal sensor...                                  No 
Some Super I/O chips contain embedded sensors. We have to write to 
standard I/O ports to probe them. This is usually safe. 
Do you want to scan for Super I/O sensors? (YES/no): yes 
Probing for Super-I/O at 0x2e/0x2f 
Trying family `National Semiconductor/ITE'...               No 
Trying family `SMSC'...                                     No 
Trying family `VIA/Winbond/Nuvoton/Fintek'...               No 
Trying family `ITE'...                                      No 
Probing for Super-I/O at 0x4e/0x4f 
Trying family `National Semiconductor/ITE'...               No 
Trying family `SMSC'...                                     No 
Trying family `VIA/Winbond/Nuvoton/Fintek'...               No 
Trying family `ITE'...                                      No 
Some hardware monitoring chips are accessible through the ISA I/O ports. 
We have to write to arbitrary I/O ports to probe them. This is usually 
safe though. Yes, you do have ISA I/O ports even if you do not have any 
ISA slots! Do you want to scan the ISA I/O ports? (YES/no): yes 
Probing for `National Semiconductor LM78' at 0x290...       No 
Probing for `National Semiconductor LM79' at 0x290...       No 
Probing for `Winbond W83781D' at 0x290...                   No 
Probing for `Winbond W83782D' at 0x290...                   No 
Lastly, we can probe the I2C/SMBus adapters for connected hardware 
monitoring devices. This is the most risky part, and while it works 
reasonably well on most systems, it has been reported to cause trouble 
on some systems. 
Do you want to probe the I2C/SMBus adapters now? (YES/no): yes 
Using driver `i2c-i801' for device 0000:00:1f.3: Intel Cougar Point (PCH) 
Module i2c-dev loaded successfully. 
Next adapter: SMBus I801 adapter at e000 (i2c-0) 
Do you want to scan it? (YES/no/selectively): yes 
Client found at address 0x50 
Probing for `Analog Devices ADM1033'...                     No 
Probing for `Analog Devices ADM1034'...                     No 
Probing for `SPD EEPROM'...                                 Yes 
    (confidence 8, not a hardware monitoring chip) 
Probing for `EDID EEPROM'...                                No 
Client found at address 0x51 
Probing for `Analog Devices ADM1033'...                     No 
Probing for `Analog Devices ADM1034'...                     No 
Probing for `SPD EEPROM'...                                 Yes 
    (confidence 8, not a hardware monitoring chip) 
Client found at address 0x52 
Probing for `Analog Devices ADM1033'...                     No 
Probing for `Analog Devices ADM1034'...                     No 
Probing for `SPD EEPROM'...                                 Yes 
    (confidence 8, not a hardware monitoring chip) 
Client found at address 0x53 
Probing for `Analog Devices ADM1033'...                     No 
Probing for `Analog Devices ADM1034'...                     No 
Probing for `SPD EEPROM'...                                 yeYes 
    (confidence 8, not a hardware monitoring chip) 
Next adapter: NVIDIA i2c adapter 0 at 1:00.0 (i2c-1) 
Do you want to scan it? (yes/NO/selectively): s 
Next adapter: NVIDIA i2c adapter 1 at 1:00.0 (i2c-2) 
Do you want to scan it? (yes/NO/selectively): yes 
Next adapter: NVIDIA i2c adapter 2 at 1:00.0 (i2c-3) 
Do you want to scan it? (yes/NO/selectively): yes 
Next adapter: NVIDIA i2c adapter 5 at 1:00.0 (i2c-4) 
Do you want to scan it? (yes/NO/selectively): yes 
Next adapter: NVIDIA i2c adapter 6 at 1:00.0 (i2c-5) 
Do you want to scan it? (yes/NO/selectively): yes 
Now follows a summary of the probes I have just done. 
Just press ENTER to continue: 
Driver `coretemp': 
  * Chip `Intel digital thermal sensor' (confidence: 9) 
Do you want to overwrite /etc/conf.d/lm_sensors? (YES/no): no 
To load everything that is needed, add this to one of the system 
initialization scripts (e.g. /etc/rc.d/rc.local): 
#----cut here---- 
# Chip drivers 
modprobe coretemp 
/usr/bin/sensors -s 
#----cut here---- 
You really should try these commands right now to make sure everything 
is working properly. Monitoring programs won't work until the needed 
modules are loaded. 
Unloading i2c-dev... OK 
Unloading cpuid... OK

**Comment by olysonek** [comment]
Hi,

I assume `sensors` displays no data from the chip even with the `it87` driver loaded? ITE chips have poor support in the kernel due to the lack of documentation for the chips. And without documentation or kernel support, I'm unable to add `sensors-detect` support.

See the other ITE-related issues. You might find some useful info there.

**Comment by RonnySvedman** [comment]
the it87 driver is hard to get precompiled and has historically needed lots of updates. Since the maintainer gave up in 2018, the in-kernel version is very old by now, or completely missing in ubuntu 20.04, but the newer source is floating out there. i compiled [https://github.com/a1wong/it87],  and now  my IT8606 works but gives bogus values on all but a few things, so YMMV - you need to edit scales and stuff in sensors3.conf, especially voltages and speeds, once you get the module compiled and working.

Asus Z97P owner since 2013

**Comment by mohamadali-halwani** [comment]
> the it87 driver is hard to get precompiled and has historically needed lots of updates. Since the maintainer gave up in 2018, the in-kernel version is very old by now, or completely missing in ubuntu 20.04, but the newer source is floating out there. i compiled [https://github.com/a1wong/it87], and now my IT8606 works but gives bogus values on all but a few things, so YMMV - you need to edit scales and stuff in sensors3.conf, especially voltages and speeds, once you get the module compiled and working.
> 
> Asus Z97P owner since 2013

Thanks for your reply, I wanted to get my chip supported so I can manipulate the fans and all.
But thanks to [Notebook Fan Control (nbfc)](https://github.com/hirschmann/nbfc/) I found that they already support a model that is very similar to my notebook, once I obtained its config file, the tool worked just fine and I am able to control my fans with ease.

But it would still be awesome if the chip was supported.

**Anyway... This experience made me understand that I need to be more conscious in my tech choices in the future. So I would never buy from ASUS or any close-sourced laptop. It's so unreasonable that they refuse to publish datasheets of their product even if they're SO OLD. I mean I bought the laptop, can't I know how did you make it? I respect the competition of the market and all, but you can at least publish the datasheets for any outdated model, it won't harm them that much, and it would benefit me as a customer.**
