### ISSUE TITLE
lm-sensors showing 0rpm radeon amdgpu 

### ISSUE THREAD

**Issue by shanestonk** [lm-sensors/lm-sensors#356]
Currently using hd7750 amdgpu card and when checking with lm-sensors it show 0rpm fan speed. it take sensors at amd-pci-0100.

When i check at cat /sys/class/drm/card0/device/hwmon/hwmon0/pwm1

there is value keep changing.

**Comment by Wer-Wolf** [comment]
The value reported as fan speed is stored in file fanX_input, the file pwm1 is for controlling the fans pwm duty cycle.
Likely the fan on your card can be controlled with pwm, but does not support fan speed reporting in RPM.
