### ISSUE TITLE
Use lm-sensors in a confined environment

### ISSUE THREAD

**Issue by wiiznokes** [lm-sensors/lm-sensors#490]
I'm trying to use libsensors in a flatpak application. I get this error:
```
failed to init libsensor: sensors_init() failed: [4] Kernel interface error
```

Is it possible to make this works ? Maybe by using udev rules, but i don't know anything about it.

**Comment by Wer-Wolf** [comment]
The library needs direct access to the kernel sysfs interface, something the container software will likely not allow by default.

**Comment by wiiznokes** [comment]
After adding `--filesystem=/sys:ro` to `finish-args`, `sensors_init` now works!
