### ISSUE TITLE
Reflect new lm-sensors webpage

### ISSUE THREAD

**Issue by msehnout** [lm-sensors/lm-sensors#8]
It seems that the lm-sensors web page is moving here:
[hwmon.wiki.kernel.org](https://hwmon.wiki.kernel.org/)

Source code should reflect that change, because it is referencing the previous web page many times:

```
$ git remote -v
origin  https://github.com/groeck/lm-sensors.git (fetch)
origin  https://github.com/groeck/lm-sensors.git (push)
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
$ git grep lm-sensors.org | wc -l
37
```

**Comment by terrycloth** [comment]
Moreover, lm-sensors.org seems to be dead. At least, it was when I tried to visit the site tonight.

**Comment by groeck** [comment]
See README.

**Comment by olysonek** [comment]
> See README.

No longer relevant. Reopening. I'll fix this issue as soon as I can.
